import { inngest } from './client'
import { createClient } from '@supabase/supabase-js'
import { google } from 'googleapis'
import { logger } from '@/lib/logger'

const REPO = process.env.GITHUB_REPO ?? 'bereniketech/content-engine'
const GITHUB_TOKEN = process.env.GITHUB_TOKEN ?? ''

async function commitToRepo(path: string, content: string): Promise<void> {
  if (!GITHUB_TOKEN) return
  const encoded = Buffer.from(content).toString('base64')
  const shaRes = await fetch(
    `https://api.github.com/repos/${REPO}/contents/${path}`,
    { headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28' } }
  )
  const sha = shaRes.ok ? (await shaRes.json() as { sha?: string }).sha : undefined

  await fetch(
    `https://api.github.com/repos/${REPO}/contents/${path}`,
    {
      method: 'PUT',
      headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28', 'Content-Type': 'application/json' },
      body: JSON.stringify({ message: `aios: analytics snapshot ${new Date().toISOString().slice(0, 10)}`, content: encoded, ...(sha ? { sha } : {}) }),
    }
  )
}

async function fetchUserCount(): Promise<number> {
  try {
    const supabase = createClient(
      process.env.NEXT_PUBLIC_SUPABASE_URL!,
      process.env.SUPABASE_SERVICE_ROLE_KEY!
    )
    const { count } = await supabase.from('profiles').select('id', { count: 'exact', head: true })
    return count ?? 0
  } catch {
    return 0
  }
}

export const aiosAnalyticsSnapshot = inngest.createFunction(
  { id: 'aios-analytics-snapshot', name: 'AIOS Analytics Snapshot' },
  { cron: '0 9 * * 1' },
  async ({ step }) => {
    const ga4Data = await step.run('fetch-ga4', async () => {
      try {
        const serviceAccountJson = process.env.GOOGLE_SERVICE_ACCOUNT_JSON
        const ga4PropertyId = process.env.GA4_PROPERTY_ID
        if (!serviceAccountJson || !ga4PropertyId) return null

        const credentials = JSON.parse(serviceAccountJson) as { client_email: string; private_key: string }
        const auth = new google.auth.GoogleAuth({ credentials, scopes: ['https://www.googleapis.com/auth/analytics.readonly'] })
        const analyticsData = google.analyticsdata({ version: 'v1beta', auth })

        const { data } = await analyticsData.properties.runReport({
          property: `properties/${ga4PropertyId}`,
          requestBody: {
            dateRanges: [{ startDate: '7daysAgo', endDate: 'today' }],
            metrics: [{ name: 'sessions' }, { name: 'screenPageViews' }],
            dimensions: [{ name: 'pagePath' }],
            orderBys: [{ metric: { metricName: 'screenPageViews' }, desc: true }],
            limit: '5',
          },
        })

        const totals = data.totals?.[0]?.metricValues ?? []
        return {
          sessions: parseInt(totals[0]?.value ?? '0', 10),
          pageViews: parseInt(totals[1]?.value ?? '0', 10),
          topPages: (data.rows ?? []).map(r => ({
            path: r.dimensionValues?.[0]?.value ?? '',
            views: parseInt(r.metricValues?.[1]?.value ?? '0', 10),
          })),
        }
      } catch (err) {
        logger.warn({ err }, 'GA4 fetch failed — check GOOGLE_SERVICE_ACCOUNT_JSON and GA4_PROPERTY_ID')
        return null
      }
    })

    const userCount = await step.run('fetch-user-count', fetchUserCount)

    const markdown = await step.run('build-snapshot', async () => {
      const date = new Date().toISOString().slice(0, 10)
      const lines = [
        `# Analytics Snapshot — ${date}`,
        '',
        '## Users',
        `- Total registered users: ${userCount}`,
        '',
        '## Web Traffic (last 30 days)',
      ]

      if (ga4Data) {
        lines.push(
          `- Sessions: ${ga4Data.sessions.toLocaleString()}`,
          `- Page views: ${ga4Data.pageViews.toLocaleString()}`,
          '',
          '## Top Pages',
          ...ga4Data.topPages.map(p => `- \`${p.path}\` — ${p.views.toLocaleString()} views`),
        )
      } else {
        lines.push('- _GA4 data unavailable — check GOOGLE_SERVICE_ACCOUNT_JSON env var_')
      }

      lines.push('', `_Generated by AIOS cadence · ${new Date().toISOString()}_`)
      return lines.join('\n')
    })

    await step.run('commit-snapshot', async () => {
      await commitToRepo('context/analytics-snapshot.md', markdown)
    })

    logger.info({ userCount, haGa4: !!ga4Data }, 'AIOS analytics snapshot complete')
    return { date: new Date().toISOString().slice(0, 10), userCount, hasGa4: !!ga4Data }
  }
)
