import { inngest } from './client'
import { logger } from '@/lib/logger'

const REPO = process.env.GITHUB_REPO ?? 'bereniketech/content-engine'
const GITHUB_TOKEN = process.env.GITHUB_TOKEN ?? ''

async function fetchPrioritiesFromRepo(): Promise<string> {
  if (!GITHUB_TOKEN) return ''
  const res = await fetch(
    `https://api.github.com/repos/${REPO}/contents/context/priorities.md`,
    { headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28' } }
  )
  if (!res.ok) return ''
  const file = await res.json() as { content?: string }
  return file.content ? Buffer.from(file.content, 'base64').toString('utf8') : ''
}

async function fetchRecentDecisions(): Promise<string[]> {
  if (!GITHUB_TOKEN) return []
  const res = await fetch(
    `https://api.github.com/repos/${REPO}/contents/decisions`,
    { headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28' } }
  )
  if (!res.ok) return []
  const files = await res.json() as Array<{ name: string }>
  return files
    .map(f => f.name)
    .filter(n => n.endsWith('.md'))
    .sort()
    .slice(-3)
}

async function commitToRepo(path: string, content: string): Promise<void> {
  if (!GITHUB_TOKEN) return
  const encoded = Buffer.from(content).toString('base64')
  const shaRes = await fetch(
    `https://api.github.com/repos/${REPO}/contents/${path}`,
    { headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28' } }
  )
  const sha = shaRes.ok ? (await shaRes.json() as { sha?: string }).sha : undefined

  await fetch(
    `https://api.github.com/repos/${REPO}/contents/${path}`,
    {
      method: 'PUT',
      headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28', 'Content-Type': 'application/json' },
      body: JSON.stringify({ message: `aios: weekly review ${new Date().toISOString().slice(0, 10)}`, content: encoded, ...(sha ? { sha } : {}) }),
    }
  )
}

export const aiosWeeklyReview = inngest.createFunction(
  { id: 'aios-weekly-review', name: 'AIOS Weekly Review', triggers: [{ cron: '0 9 * * 1' }] },
  async ({ step }) => {
    const priorities = await step.run('fetch-priorities', fetchPrioritiesFromRepo)
    const recentDecisions = await step.run('fetch-decisions', fetchRecentDecisions)

    const markdown = await step.run('build-review', async () => {
      const date = new Date().toISOString().slice(0, 10)
      const hasPriorities = priorities && !priorities.includes('Run /aios-onboard')

      return [
        `# Weekly Review — ${date}`,
        '',
        '## Priorities Status',
        hasPriorities
          ? priorities
          : '_priorities.md not yet populated — run /aios-onboard_',
        '',
        '## Recent Decisions',
        recentDecisions.length > 0
          ? recentDecisions.map(f => `- ${f}`).join('\n')
          : '- No decisions logged yet',
        '',
        '## Recommendation',
        hasPriorities
          ? '_Review the priorities above. Update context/priorities.md if goals have shifted._'
          : '_Run /aios-onboard to populate priorities before the next weekly review._',
        '',
        `_Generated by AIOS cadence · ${new Date().toISOString()}_`,
      ].join('\n')
    })

    await step.run('commit-review', async () => {
      const date = new Date().toISOString().slice(0, 10)
      await commitToRepo(`context/weekly-review-${date}.md`, markdown)
    })

    logger.info({ date: new Date().toISOString().slice(0, 10) }, 'AIOS weekly review complete')
    return { date: new Date().toISOString().slice(0, 10) }
  }
)
