import { inngest } from './client'
import { logger } from '@/lib/logger'

const REPO = process.env.GITHUB_REPO ?? 'bereniketech/content-engine'
const GITHUB_TOKEN = process.env.GITHUB_TOKEN ?? ''

async function fetchOpenIssues(): Promise<Array<{ title: string; number: number; labels: string[] }>> {
  if (!GITHUB_TOKEN) return []
  const res = await fetch(
    `https://api.github.com/repos/${REPO}/issues?state=open&per_page=20`,
    { headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28' } }
  )
  if (!res.ok) return []
  const issues = await res.json() as Array<{ title: string; number: number; labels: Array<{ name: string }> }>
  return issues.map(i => ({ title: i.title, number: i.number, labels: i.labels.map(l => l.name) }))
}

async function commitToRepo(path: string, content: string): Promise<void> {
  if (!GITHUB_TOKEN) return
  const encoded = Buffer.from(content).toString('base64')
  const shaRes = await fetch(
    `https://api.github.com/repos/${REPO}/contents/${path}`,
    { headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28' } }
  )
  const sha = shaRes.ok ? (await shaRes.json() as { sha?: string }).sha : undefined

  await fetch(
    `https://api.github.com/repos/${REPO}/contents/${path}`,
    {
      method: 'PUT',
      headers: { Authorization: `Bearer ${GITHUB_TOKEN}`, 'X-GitHub-Api-Version': '2022-11-28', 'Content-Type': 'application/json' },
      body: JSON.stringify({ message: `aios: daily standup ${new Date().toISOString().slice(0, 10)}`, content: encoded, ...(sha ? { sha } : {}) }),
    }
  )
}

export const aiosDailyStandup = inngest.createFunction(
  { id: 'aios-daily-standup', name: 'AIOS Daily Stand-Up' },
  { cron: '0 8 * * *' },
  async ({ step }) => {
    const issues = await step.run('fetch-github-issues', fetchOpenIssues)

    const markdown = await step.run('build-standup', async () => {
      const date = new Date().toISOString().slice(0, 10)
      const top3 = issues.slice(0, 3)
      const blocked = issues.filter(i => i.labels.includes('blocked'))

      return [
        `# Stand-Up — ${date}`,
        '',
        '## Top focus items',
        ...top3.map((i, n) => `${n + 1}. #${i.number} ${i.title}`),
        top3.length === 0 ? '_No open issues found — check GitHub or .spec/tasks/_' : '',
        '',
        '## Blocked',
        blocked.length > 0 ? blocked.map(i => `- #${i.number} ${i.title}`).join('\n') : '- none',
        '',
        `_Generated by AIOS cadence · ${new Date().toISOString()}_`,
      ].join('\n')
    })

    await step.run('commit-standup', async () => {
      const date = new Date().toISOString().slice(0, 10)
      await commitToRepo(`context/standup-${date}.md`, markdown)
    })

    logger.info({ issueCount: issues.length }, 'AIOS daily standup complete')
    return { date: new Date().toISOString().slice(0, 10), issueCount: issues.length }
  }
)
